//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaPerf.ManagerPdf.Security {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceActiveDirectory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceActiveDirectory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaPerf.ManagerPdf.Security.ResourceActiveDirectory", typeof(ResourceActiveDirectory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mediaperf.
        /// </summary>
        internal static string DomaineActiveDirectory {
            get {
                return ResourceManager.GetString("DomaineActiveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wyniwygidf.
        /// </summary>
        internal static string DomaineActiveDirectory_WYNIWYG {
            get {
                return ResourceManager.GetString("DomaineActiveDirectory_WYNIWYG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usiuser.
        /// </summary>
        internal static string LoginUtilisateurBaseDeDonnees {
            get {
                return ResourceManager.GetString("LoginUtilisateurBaseDeDonnees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLUser.
        /// </summary>
        internal static string LoginUtilisateurBaseDeDonnees_WYNIWYG {
            get {
                return ResourceManager.GetString("LoginUtilisateurBaseDeDonnees_WYNIWYG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur non reconnu dans Active Directory. Veuillez contacter votre administateur.
        /// </summary>
        internal static string MessageErreurActiveDirectory {
            get {
                return ResourceManager.GetString("MessageErreurActiveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur non reconnu dans Active Directory. Veuillez contacter votre administateur.
        /// </summary>
        internal static string MessageErreurActiveDirectory_WYNIWYG {
            get {
                return ResourceManager.GetString("MessageErreurActiveDirectory_WYNIWYG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usiuser.
        /// </summary>
        internal static string PswUtilisateurBaseDeDonnees {
            get {
                return ResourceManager.GetString("PswUtilisateurBaseDeDonnees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLUser.
        /// </summary>
        internal static string PswUtilisateurBaseDeDonnees_WYNIWYG {
            get {
                return ResourceManager.GetString("PswUtilisateurBaseDeDonnees_WYNIWYG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP://.
        /// </summary>
        internal static string TypeAnnuaireActiveDirectory {
            get {
                return ResourceManager.GetString("TypeAnnuaireActiveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP://.
        /// </summary>
        internal static string TypeAnnuaireActiveDirectory_WYNIWYG {
            get {
                return ResourceManager.GetString("TypeAnnuaireActiveDirectory_WYNIWYG", resourceCulture);
            }
        }
    }
}
